// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  D1_POSTS: D1Database;
  R2_BUCKET: R2Bucket;
  R2_IMAGES_BASE_URL: string;
  POSTS_API_TOKEN: string;
}
