services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    volumes:
      - .:/home/node/app
    tty: true
    working_dir: /home/node/app
